version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - wepost-network
  backend:
    container_name: wepost-backend-container_name
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - wepost-network

volumes:
  pgdata:


networks:
  wepost-network:
