version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wepost

volumes:
  pgdata:
